language: node_js
os: osx
node_js:
  - "12"
addons:
  apt:
    packages:
      - xvfb
branches:
  only:
    - master
    - develop
    - "/^v.*$/"
before_script:
  - "export DISPLAY=:99.0"
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
before_deploy:
  - npm run prerelease
deploy:
  - provider: releases
    edge: true
    skip_cleanup: true
    api_key:
      secure: hRui6rjKyfnlO7FsNxxrOBJQmJ9jO/ofe3FGgnelkDPUpT0i9ifSKVASKDErxfIXyZjKACdK+wqaRvATdvVDv7Bd4p9rZr+7nAnIpzq9QZZTp0NhZiBY4YOfa3evEuJIhJV2QExX+kVW2wGtaAUkVn3cTp2y5F4CRlqdqoLtfuv6Zk+SzfUIi3OlrR2hhioSwbssTrRADICbemtuRFssTyRiqYUldYWQDJxZx5wsrrvXqI3/mvpoxE0mO12KbaYGxIkkqk72VIX9TzH+gxqv1AX0JJNW6SVSrqfh/PmzmeYNLslozsayoQZrFih4TeKPjSNF7w3jjbEv1VAZRKzytRaIgIkxhhYizZdemJ+DA07C/OOv2aLUYL9gliqs9tBAtC8iGRbb/ns6sg35t762dK2riKei1xNbfFQj5cbJhysbwodorVzm10VfHs9cxDEoGBSvIkYVQwU3F2dKIPr781rgLoKXuNEROedPA0TmqNl3r36XRYvz2NUMP4kAaJ52YGx785dbMWMOs9hRxJKzujCpoMooggEClofyQqpOvZ8t7k6Z3CiCZibj7LLpU6PlCLxIiP/xm5XjKINBBMeIGIX7t0xrn9JMV/GKkZWZhYNlQqd+Ls3nEAN6R5eS09lYfp1vQ/i2la33sXQVtxTwv1M8Ftq6PFHsrSh0QHE+WNM=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/svelte-simple-modal
  - provider: npm
    edge: true
    skip_cleanup: true
    email: code@lekschas.de
    api_key:
      secure: Ortl/2lh1ZDt4/oIIAhEqDt/2RUHJ7bvad+3uo1cc6XhfdxgHgXjXsVqNFduBAL5xVf/NKwBcSgai1yVZEvDhsGifA04qGP1sT3pagtVZx6oYDJbfZXKt8+l8kl+uLQ0ucExQ1eIQxCCLKYm5ZsbQgHy5/OgZyW9a6qjeGJLWXtV9HwKUqASDp+Vm2Qugls77oVuEOcnsxRPOyxIOOvIw8HVGWcAesucUeS9sRtiva6TCVa0CylOtszLuz/og1qXiTRAVP3hBDpeeqfAgzeiW/ACMxj/szfpfeLUZnRatmA+90BB5uM2oi20Lu0Se5qm7Tt/JTVHsl2Fot3ZEu8fmx+eKm9tZ6PkGG4zPFX2/mJ/Kvs8ANWkqcjYgF9APVH+/YeBgeBUwDOUvs406IAyUUT5ggvUQqJvZoK7Hiiz7mIcUwAMwDJhkKa+oYtRlyalzTdvSfnvTzdWYuDHaeP5aJ9VqsB+JMYnAbM41Ldg9zy7he+6FTIFtgIPDJQlUCQndRhDkBJbE+bEnTbVKFK8CEqtUx7ec2Ilv7uV1pl+Ic7N9f33mDEKYD23pMRD4n1exfI7psykPvh+LXNnKg+mBfJr8S/A6OcqmNZJNINR5r6ktcnkTsOEHjFWfOenmzFIRFKAkAkzcT4AcYL0wlaK2z4zMB1W824bMCEkhvY2Xb4=
    on:
      branch: master
      tags: true
      repo: flekschas/svelte-simple-modal
