language: node_js
os: osx
node_js:
  - "8"
addons:
  apt:
    packages:
      - xvfb
branches:
  only:
    - master
    - develop
    - "/^v.*$/"
before_script:
  - "export DISPLAY=:99.0"
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
before_deploy:
  - npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: hRui6rjKyfnlO7FsNxxrOBJQmJ9jO/ofe3FGgnelkDPUpT0i9ifSKVASKDErxfIXyZjKACdK+wqaRvATdvVDv7Bd4p9rZr+7nAnIpzq9QZZTp0NhZiBY4YOfa3evEuJIhJV2QExX+kVW2wGtaAUkVn3cTp2y5F4CRlqdqoLtfuv6Zk+SzfUIi3OlrR2hhioSwbssTrRADICbemtuRFssTyRiqYUldYWQDJxZx5wsrrvXqI3/mvpoxE0mO12KbaYGxIkkqk72VIX9TzH+gxqv1AX0JJNW6SVSrqfh/PmzmeYNLslozsayoQZrFih4TeKPjSNF7w3jjbEv1VAZRKzytRaIgIkxhhYizZdemJ+DA07C/OOv2aLUYL9gliqs9tBAtC8iGRbb/ns6sg35t762dK2riKei1xNbfFQj5cbJhysbwodorVzm10VfHs9cxDEoGBSvIkYVQwU3F2dKIPr781rgLoKXuNEROedPA0TmqNl3r36XRYvz2NUMP4kAaJ52YGx785dbMWMOs9hRxJKzujCpoMooggEClofyQqpOvZ8t7k6Z3CiCZibj7LLpU6PlCLxIiP/xm5XjKINBBMeIGIX7t0xrn9JMV/GKkZWZhYNlQqd+Ls3nEAN6R5eS09lYfp1vQ/i2la33sXQVtxTwv1M8Ftq6PFHsrSh0QHE+WNM=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/svelte-simple-modal
  - provider: npm
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: aTW+q6Al9i41L7I90f0TCnBWBKZ526IpQIjR4tjzPa1UDCtt5MsA5EXcswO2GtuNHeV8QkC7lSPMWmr7SLNWIBXQQ4wSy49gqpqxH2gQ3uoRYYqU3c9/OnJbKlNoCyJx8KP3FO3+kWL6dsOC3vcMkObhAB6qBbx5GqE+tlq8zhFbDriJ7qrofkWkqanukQORDeHcUPlBcjwfaBDo6EInQ7HLf0b58yRF/zqM8k6D8lmPBsNOywhe2/8Jez6aEsTZ14vQo0PD36omXIaTztqFoEim001PM6dXLm4YF8y9g6Ru+WDk+zppOfVciHZpMBz7ox2gPlKnd/Wkvpn0y54GSpK2HqsCHvN0LuDCWToUw7mi1gO0yncZ+Zu/F9gbqYNMfc29ax3R3UXom0G2t7teQhJYkzbi/atrPe2/MBvEcwJmGGi94Pf0E6R5Virjsz8PnxxMpQspNuxNsb6NOh3QrPKyGELjsP31zlxE2y9b4cW3DZmFqDHojrBwsmTryddy2jlPiwRDwtkFRVWAXoDOqui4r/+PBWVtxZvj69NUZq45XPgKuS/2snDl0deyyNaFDN+JTIoMeUCuy55mZRXRq494omoPq8oBQC/QZ7ZE8U2qxIaR+xzpnFGgi397ANeK2y/rOcspKc6IKbRbvOpN4TZtm9CSDKoYFUNfeKxOcOo=
    on:
      branch: master
      tags: true
      repo: flekschas/svelte-simple-modal
